---
title: "Resultados ACP"
author: "Erick Vázquez"
date: "23 de Agosto del 2023"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    collapsed: yes
    smooth_scroll: yes
    theme: readable
    highlight: zenburn
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(dplyr)
library(ggprism) ## minor thicks
library(FactoMineR)
library(ggfortify)
library(plotly)
library(factoextra)
library(GGally)
library(skimr)
library(car)

setwd("D:\\Documentos\\Biologia UAM X\\SERVICIO\\SuelosBD\\cvs")

mk1 <- read.csv("MK1.csv")
mk2 <- read.csv("MK2.csv")
mk3 <- read.csv("MK3.csv")
mk3 <- read.csv("MK3.csv")
ml1 <- read.csv("ML1.csv")
ml2 <- read.csv("ML2.csv")
ml3 <- read.csv("ML3.csv")
mp1 <- read.csv("MP1.csv")
mp2 <- read.csv("MP2.csv")
mp3 <- read.csv("MP3.csv")

sk1 <- read.csv("SK1.csv")
sk2 <- read.csv("SK2.csv")
sk3 <- read.csv("SK3.csv")
sk3 <- read.csv("SK3.csv")
sl1 <- read.csv("SL1.csv")
sl2 <- read.csv("SL2.csv")
sl3 <- read.csv("SL3.csv")
sp1 <- read.csv("SP1.csv")
sp2 <- read.csv("SP2.csv")
sp3 <- read.csv("SP3.csv")
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
## Df todas

## Mantillo
df_mq <- data.frame(
  Total_OM_loss = c(mk1$Total.OM.loss....[1], mk2$Total.OM.loss....[1], mk3$Total.OM.loss....[1], ml1$Total.OM.loss....[1],
                    ml2$Total.OM.loss....[1], ml3$Total.OM.loss....[1], mp1$Total.OM.loss....[1], mp2$Total.OM.loss....[1], mp3$Total.OM.loss....[1]),
  QReleased = c(mk1$Total.Q.released..J.g.1.[1],mk2$Total.Q.released..J.g.1.[1], mk3$Total.Q.released..J.g.1.[1],
                ml1$Total.Q.released..J.g.1.[1], ml2$Total.Q.released..J.g.1.[1], ml3$Total.Q.released..J.g.1.[1],
                mp1$Total.Q.released..J.g.1.[1], mp2$Total.Q.released..J.g.1.[1], mp3$Total.Q.released..J.g.1.[1]),
  Q = c(mk1$Q....J.mg.1.OM.[1], mk2$Q....J.mg.1.OM.[1], mk3$Q....J.mg.1.OM.[1], ml1$Q....J.mg.1.OM.[1],
         ml2$Q....J.mg.1.OM.[1], ml3$Q....J.mg.1.OM.[1], mp1$Q....J.mg.1.OM.[1], mp2$Q....J.mg.1.OM.[1], mp3$Q....J.mg.1.OM.[1]),
  Q50 = c(mk1$Q50..J.g.1.[1], mk2$Q50..J.g.1.[1], mk3$Q50..J.g.1.[1], ml1$Q50..J.g.1.[1],
         ml2$Q50..J.g.1.[1], ml3$Q50..J.g.1.[1], mp1$Q50..J.g.1.[1], mp2$Q50..J.g.1.[1], mp3$Q50..J.g.1.[1]),
  T50 = c(mk1$T50Q..oC.[1], mk2$T50Q..oC.[1], mk3$T50Q..oC.[1], ml1$T50Q..oC.[1],
         ml2$T50Q..oC.[1], ml3$T50Q..oC.[1], mp1$T50Q..oC.[1], mp2$T50Q..oC.[1], mp3$T50Q..oC.[1]),
  Q1 = c(mk1$Q1....[1], mk2$Q1....[1], mk3$Q1....[1], ml1$Q1....[1],
            ml2$Q1....[1], ml3$Q1....[1], mp1$Q1....[1], mp2$Q1....[1], mp3$Q1....[1]),
  Q2= c(mk1$Q2....[1], mk2$Q2....[1], mk3$Q2....[1], ml1$Q2....[1], 
        ml2$Q2....[1], ml3$Q2....[1], mp1$Q2....[1], mp2$Q2....[1], mp3$Q2....[1]),
  Q3= c(mk1$Q3....[1], mk2$Q3....[1], mk3$Q3....[1], ml1$Q3....[1], 
        ml2$Q3....[1], ml3$Q3....[1], mp1$Q3....[1], mp2$Q3....[1], mp3$Q3....[1]),
  T1= c(mk1$T1Q...oC.[1], mk2$T1Q...oC.[1], mk3$T1Q...oC.[1], ml1$T1Q...oC.[1], 
        ml2$T1Q...oC.[1], ml3$T1Q...oC.[1], mp1$T1Q...oC.[1], mp2$T1Q...oC.[1], mp3$T1Q...oC.[1]),
  T2= c(mk1$T2Q...oC.[1], mk2$T2Q...oC.[1], mk3$T2Q...oC.[1], ml1$T2Q...oC.[1], 
        ml2$T2Q...oC.[1], ml3$T2Q...oC.[1], mp1$T2Q...oC.[1], mp2$T2Q...oC.[1], mp3$T2Q...oC.[1]),
  T3= c(mk1$T3Q...oC.[1], mk2$T3Q...oC.[1], mk3$T3Q...oC.[1], ml1$T3Q...oC.[1], 
        ml2$T3Q...oC.[1], ml3$T3Q...oC.[1], mp1$T3Q...oC.[1], mp2$T3Q...oC.[1], mp3$T3Q...oC.[1]),
  Group = rep(c("MK", "ML", "MP"))
)


## Suelo
df_sq <- data.frame(
  Total_OM_loss = c(sk1$Total.OM.loss....[1], sk2$Total.OM.loss....[1], sk3$Total.OM.loss....[1], sl1$Total.OM.loss....[1],
                    sl2$Total.OM.loss....[1], sl3$Total.OM.loss....[1], sp1$Total.OM.loss....[1], sp2$Total.OM.loss....[1], sp3$Total.OM.loss....[1]),
  QReleased = c(sk1$Total.Q.released..J.g.1.[1],sk2$Total.Q.released..J.g.1.[1], sk3$Total.Q.released..J.g.1.[1],
                sl1$Total.Q.released..J.g.1.[1], sl2$Total.Q.released..J.g.1.[1], sl3$Total.Q.released..J.g.1.[1],
                sp1$Total.Q.released..J.g.1.[1], sp2$Total.Q.released..J.g.1.[1], sp3$Total.Q.released..J.g.1.[1]),
  Q = c(sk1$Q....J.mg.1.OM.[1], sk2$Q....J.mg.1.OM.[1], sk3$Q....J.mg.1.OM.[1], sl1$Q....J.mg.1.OM.[1],
        sl2$Q....J.mg.1.OM.[1], sl3$Q....J.mg.1.OM.[1], sp1$Q....J.mg.1.OM.[1], sp2$Q....J.mg.1.OM.[1], sp3$Q....J.mg.1.OM.[1]),
  Q50 = c(sk1$Q50..J.g.1.[1], sk2$Q50..J.g.1.[1], sk3$Q50..J.g.1.[1], sl1$Q50..J.g.1.[1],
          sl2$Q50..J.g.1.[1], sl3$Q50..J.g.1.[1], sp1$Q50..J.g.1.[1], sp2$Q50..J.g.1.[1], sp3$Q50..J.g.1.[1]),
  T50 = c(sk1$T50Q..oC.[1], sk2$T50Q..oC.[1], sk3$T50Q..oC.[1], sl1$T50Q..oC.[1],
          sl2$T50Q..oC.[1], sl3$T50Q..oC.[1], sp1$T50Q..oC.[1], sp2$T50Q..oC.[1], sp3$T50Q..oC.[1]),
  Q1 = c(sk1$Q1....[1], sk2$Q1....[1], sk3$Q1....[1], sl1$Q1....[1],
         sl2$Q1....[1], sl3$Q1....[1], sp1$Q1....[1], sp2$Q1....[1], sp3$Q1....[1]),
  Q2= c(sk1$Q2....[1], sk2$Q2....[1], sk3$Q2....[1], sl1$Q2....[1], 
        sl2$Q2....[1], sl3$Q2....[1], sp1$Q2....[1], sp2$Q2....[1], sp3$Q2....[1]),
  Q3= c(sk1$Q3....[1], sk2$Q3....[1], sk3$Q3....[1], sl1$Q3....[1], 
        sl2$Q3....[1], sl3$Q3....[1], sp1$Q3....[1], sp2$Q3....[1], sp3$Q3....[1]),
  T1= c(sk1$T1Q...oC.[1], sk2$T1Q...oC.[1], sk3$T1Q...oC.[1], sl1$T1Q...oC.[1], 
        sl2$T1Q...oC.[1], sl3$T1Q...oC.[1], sp1$T1Q...oC.[1], sp2$T1Q...oC.[1], sp3$T1Q...oC.[1]),
  T2= c(sk1$T2Q...oC.[1], sk2$T2Q...oC.[1], sk3$T2Q...oC.[1], sl1$T2Q...oC.[1], 
        sl2$T2Q...oC.[1], sl3$T2Q...oC.[1], sp1$T2Q...oC.[1], sp2$T2Q...oC.[1], sp3$T2Q...oC.[1]),
  T3= c(sk1$T3Q...oC.[1], sk2$T3Q...oC.[1], sk3$T3Q...oC.[1], sl1$T3Q...oC.[1], 
        sl2$T3Q...oC.[1], sl3$T3Q...oC.[1], sp1$T3Q...oC.[1], sp2$T3Q...oC.[1], sp3$T3Q...oC.[1]),
  Group = rep(c("SK", "SL", "SP"))
)
```

## ***Mantillo***

## Datos de DSC de mantillo

```{r rows.print=10}
df_mq 
```


## *Correlacion y Covarianza*



```{r message=FALSE, warning=FALSE, echo=FALSE}
ggpairs(df_mq, columns = 2:11,
        aes(color = Group),
        upper = list(continuous = wrap("cor", size = 1.8))) +
  theme(
    text = element_text(size = 6) 
  )
```

### Covarianza
```{r message=FALSE, warning=FALSE, echo=FALSE}
## Covarianza de la matriz
cov(df_mq[,2:11])


```

### Correlación
```{r message=FALSE, warning=FALSE, echo=FALSE}
## Correlacion de la matriz
cor(df_mq[,2:11])
```

### Resúmen estadístico de ACP

```{r message=FALSE, warning=FALSE, echo=FALSE}
pc_mq <- df_mq %>% select(-Group) %>% as.matrix() %>% prcomp()
summary(pc_mq)
```


### Screeplot

```{r message=FALSE, warning=FALSE, echo=FALSE}
## Scree plot para seleccion de dimensiones
plot(pc_mq, type = "line")
```

### Estructura de componentes principales
```{r message=FALSE, warning=FALSE, echo=FALSE}
str(pc_mq)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
dfmq_pca <- PCA(df_mq[, -12], graph=F)
```

### Biplot de ACP

```{r message=FALSE, warning=FALSE, echo=FALSE}
fviz_pca_biplot(dfmq_pca, 
                habillage = as.factor(df_mq$Group), addEllipses = TRUE,
                col.var = "red", alpha.var ="cos2",
                label = "var") +
  scale_color_brewer(palette="Dark2")+
  theme_minimal()
```

## ***Suelo***

## Datos de DSC de suelo

```{r message=FALSE, warning=FALSE, echo=FALSE}
df_sq
```

## Correlacion y Covarianza

```{r message=FALSE, warning=FALSE, echo=FALSE}
ggpairs(df_sq, columns = 2:11,
        aes(color = Group),
        upper = list(continuous = wrap("cor", size = 1.8))) +
  theme(
    text = element_text(size = 6) 
  )
```

### Covarianza

```{r message=FALSE, warning=FALSE, echo=FALSE}
## Covarianza de la matriz
cov(df_sq[,2:11])
```

### Correlación

```{r message=FALSE, warning=FALSE, echo=FALSE}
## Correlacion de la matriz
cor(df_sq[,2:11])
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
pc_sq <- df_mq %>% select(-Group) %>% as.matrix() %>% prcomp()
summary(pc_sq)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
## Scree plot para seleccion de dimensiones
plot(pc_sq, type = "line")
```
## Estructura de componentes principales

```{r message=FALSE, warning=FALSE, echo=FALSE}
str(pc_sq)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
dfsq_pca <- PCA(df_sq[, -12], graph=F)
```

## Biplot de ACP
```{r message=FALSE, warning=FALSE, echo=FALSE}
fviz_pca_biplot(dfsq_pca, 
                habillage = as.factor(df_sq$Group), addEllipses = TRUE,
                col.var = "red", alpha.var ="cos2",
                label = "var") +
  scale_color_brewer(palette="Dark2")+
  theme_minimal()
```



